### ISSUE TITLE
Write a database seeder for all of the food access points

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#14]
We need to write a seeder for all of the food access points in the Upper Valley. We need to look for the information that Ashleen sent to us.

**Comment by thomascchen** [comment]
The place to do this would be in the `seeds.rb` file. There, you can just write Ruby like

```
FoodAccessPoint.create(...data...)
```

Could iterate over an array to create the access points. Need to pull these from a list that I think Ashleen provided to us at some point. Might require some manual entry... 

To seed the database, you can then run `rails db:seed` in the command line.

To wipe it all, you can run `FoodAccessPoint.delete_all`

Check out the api.rubyonrails.org documentation for more info

**Comment by bthooper** [comment]
I just forked this project and it seems to me there is no seeding at all at the moment. Is that correct? I would be happy to do this - assuming there is seed data somewhere - and it seems like having some good starter data in the app would really help with ongoing dev work.

**Comment by thomascchen** [comment]
yes @bthooper we could use a seeds file! We don't have a solid list of starter data yet, that will eventually be something that we'll need to get from our partner and seed into our database as a starting point. For now, at least for dev purposes, generating some dummy data I think would be a good starting point. I will work on getting the actual data from our partner.

**Comment by bthooper** [comment]
sounds good .. i'll make some dummy data up to at least have a little something in there

**Comment by bthooper** [comment]
submitted a pull request to seed dummy data.  it reads a csv file, so we could dump in a new csv file when/if we get real/better data

**Comment by bthooper** [comment]
Ha! I just realized that db:setup basically does this for you...I've never really used that - just used db:seed but had it work that way...so I guess seed can just seed and when you need a clean db you can use setup....like I said, my ruby is rusty!

but glad to learn something today!
