### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#15]
Food access point providers need to be able to log in in order to update their food access point details. Devise is probably be a good option.

**Comment by bthooper** [comment]
I would be willing to create an authentication model if that would be helpful. I can do it from scratch or use devise if you would prefer. Should I offer this help in the slack channel??

**Comment by thomascchen** [comment]
Yes this would helpful! I usually default to devise, seems like it would be wise to stand on the community's shoulders rather than write something from scratch?

**Comment by bthooper** [comment]
that's fine. writing from scratch isn't that much harder and I feel like i know all that is going on...but devise is battle-tested and robust...so devise it is....seed data first though

**Comment by bthooper** [comment]
i've installed devise and started applying some styling and getting it look like it's part of the app and working.  I'm wondering if we want to allow for registrations from the app - so that anyone could register - or if the registrations are really restricted to people who would need to update info on a site, in which case we might want to restrict registration in some fashion?

**Comment by bthooper** [comment]
ALso, when should I submit a PR? When it's ALL done? Or incrementally as I work on it?

**Comment by thomascchen** [comment]
> i've installed devise and started applying some styling and getting it look like it's part of the app and working. I'm wondering if we want to allow for registrations from the app - so that anyone could register - or if the registrations are really restricted to people who would need to update info on a site, in which case we might want to restrict registration in some fashion?

Just seeing your comment now, months after the fact! Let's hold off on figuring that out until we can run a minimally working version of this by Little Rivers. I think what you've done so far meets the requirements to close this issue
