### ISSUE TITLE
Form to update food access points

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#17]
### Requirements
Food access provider should be able to update their details via this form.

#### Info section
- [x] Address
- [x] Phone number
- [x] Email
- [x] Website
- [x] Additional information (Content TBD)
- [x] Typically available items

#### Hours
- [x] Open now status should be dynamic
- [x] Days and hours are shown

#### Recent arrivals
- [x] Show when this information was last updated
- [x] Show items that the provider notes are recently arrived 

#### Food details (this is what others will see and what the provider should be able to update)
<img width="375" alt="63D1E5F9-4482-41E9-A297-A5E4BA6F670B" src="https://user-images.githubusercontent.com/11340361/87863303-aa856d80-c927-11ea-9eac-8075412b3bd8.png">

#### Form "example" (not a complete design but gives the idea)
<img width="375" alt="3EEC7228-F2B1-4F16-8B12-DB31DB6AA2A5" src="https://user-images.githubusercontent.com/11340361/87863274-790ca200-c927-11ea-9cdd-ae70ee8ce003.png">

**Comment by thomascchen** [comment]
Partly addressed by #43

**Comment by siobhanjacobson** [comment]
@thomascchen I'd like to work on this one next when I have time!

**Comment by thomascchen** [comment]
Closing this as I wrapped this up today :)
