### ISSUE TITLE
Navigation menu

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#18]
### Requirements
This should be a nav bar that appears when users click the "Menu" CTA on the other pages. This should be available on every page.

- [ ] Add links to Home, About, Login, and How to use sections

#### Menu (example design, this is just a concept, open to better visual ideas)
<img width="375" alt="CE386B89-FDA1-4C93-BA3D-2E2D1EDC78C0" src="https://user-images.githubusercontent.com/11340361/87863342-2a133c80-c928-11ea-8563-e71130e4b7f4.png">
#### Another screen showing the menu CTA (just a concept, open to better visual ideas)
<img width="375" alt="6251F88A-2225-4C13-BE33-A4CF8DA9A8BA" src="https://user-images.githubusercontent.com/11340361/87863395-88401f80-c928-11ea-984c-6d1b035cbd7b.png">

**Comment by ayaz-ac** [comment]
Hey @thomascchen could you assign me this one ? I would like to try it out !
