### ISSUE TITLE
Show details of food access points

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#19]
### Requirements
Food access provider should be able to view their details via this form.

#### Info section
- [ ] Address
- [ ] Phone number
- [ ] Email
- [ ] Website
- [ ] Additional information (Content TBD)
- [ ] Typically available items

#### Hours
- [ ] Open now status should be dynamic
- [ ] Days and hours are shown

#### Recent arrivals
- [ ] Show when this information was last updated
- [ ] Show items that the provider notes are recently arrived 

### Wireframe designs
<img width="375" alt="63D1E5F9-4482-41E9-A297-A5E4BA6F670B" src="https://user-images.githubusercontent.com/11340361/87863401-92fab480-c928-11ea-8871-d9953bb35439.png">

**Comment by ayaz-ac** [comment]
@thomascchen Can i get assigned to this one ? :)
