### ISSUE TITLE
Add text search to index view

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#20]
### Requirements
- [x] Add a search box that allows the user to do a text search of the food places so they can find the food, goods, etc. they are looking for

### Wireframe designs
<img width="375" alt="6251F88A-2225-4C13-BE33-A4CF8DA9A8BA" src="https://user-images.githubusercontent.com/11340361/87863420-ca696100-c928-11ea-9a04-fe227293ea11.png">

**Comment by ayaz-ac** [comment]
@thomascchen Could i get assigned on this issue please ? 😃

**Comment by thomascchen** [comment]
Closed by #112
