### ISSUE TITLE
Add quick action to filter food access points to only those that are currently open

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#21]
### Requirements
- [ ] Add a CTA that allows users to filter the list of food access points on the list view by those that are open currently.

### Wireframe designs
<img width="375" alt="6251F88A-2225-4C13-BE33-A4CF8DA9A8BA" src="https://user-images.githubusercontent.com/11340361/87863442-f8e73c00-c928-11ea-9579-be0312b000b7.png">

**Comment by ayaz-ac** [comment]
Hello @thomascchen Is it possible to be assigned on this one ?

**Comment by thomascchen** [comment]
Closed by #108
