### ISSUE TITLE
Create "How to use" page

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#23]
We will need a page to show users how to use the app. Content TBD.

**Comment by siobhanjacobson** [comment]
@thomascchen Is this still on hold?

**Comment by thomascchen** [comment]
No this should be doable now! I'll make that clearer...

**Comment by siobhanjacobson** [comment]
I'll work on this one and #22 . @thomascchen could you please assign these to me?

**Comment by thomascchen** [comment]
closed by #65
