### ISSUE TITLE
Add schedule to food_access_points

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#26]
Food access points are open certain hours of the week. We need to add this schedule to the data model so that we can show these hours, update them, and filter on them.

This issue is focused on setting up the data model.

Some context to keep in mind for this are the following issues, which will depend on this data model:
- We should be able to render these schedules on the list and details views for food access points (#11 and #19)
- Volunteers who run these food access points will need to be able to update these hours themselves via a form (#17 )
- The app will also need to be able to filter on which food access points are open currently (#21)

**Comment by ayaz-ac** [comment]
Hey @thomascchen i can take this one ! 😄
