### ISSUE TITLE
My bug in CSV import for seeds.rb

### ISSUE THREAD

**Issue by bthooper** [codeforUV/food_resources#39]
I made a bug!

I can't figure it out...still researching. But I just noticed that my CSV import which I was using for seed data in seeds.rb for some cryptic reason isn't getting the first element of each row. Here is the code:

```ruby
csv = CSV.parse(File.read(Rails.root.join('db', 'seeds.csv')), headers: true)

csv.each do |row|
  fap = FoodAccessPoint.new
  fap.address = row["address"]
  fap.town = row["town"]
  fap.state = row["state"]
  fap.zip = row["zip"]
  fap.name = row["name"]
  fap.phone_number = row["phone_number"]
  fap.website = row["website"]
  fap.website = "http://cnn.com" unless !fap.website.blank?
  fap.save
  puts fap.name + " saved." 
end
```

So whatever column is first in the seeds.csv file, it is not getting pulled in......

**Comment by thomascchen** [comment]
oh weird! hmm just glanced at this and couldn't figure it out either.

**Comment by bthooper** [comment]
I got some ideas on how to address this from a few different angles.....let me see what i can do if anything

**Comment by davekaro** [comment]
@bthooper I just opened a PR with the fix. Let me know if you have questions!

**Comment by bthooper** [comment]
even better...thanks
