### ISSUE TITLE
Consider Open Referral's Data Specification in our data model

### ISSUE THREAD

**Issue by thomascchen** [codeforUV/food_resources#64]
Open Referral's website: https://www.openreferral.org

> Open Referral’s goal is to enable interoperability among diverse technologies that might use resource directory information to help meet people’s needs.

They are working on a [Human Services Data Specification](https://docs.openreferral.org/en/latest/hsds/reference/) and a set of protocols for "accessing, updating, exchanging and synchronizing community resource directory data."

Perhaps their standards can inform how we model our data?

**Comment by thomascchen** [comment]
I reviewed the HSDS in more detail today, and I'm really impressed by the level of thought and consideration that's evident in this work. I think the specification lends itself very well to the structuring of data in our food resources app. Reading through the specification made me aware of a number of things that we had not really considered or had glossed over in our initial thinking, particularly [`accessibility`](http://docs.openreferral.org/en/latest/hsds/reference/#accessibility_for_disabilities) and [`language`](http://docs.openreferral.org/en/latest/hsds/reference/#language) data. The design of the [`schedule`](http://docs.openreferral.org/en/latest/hsds/reference/#schedule) table is also extremely helpful as figuring out how to represent schedules is something that has been vexing me. I think what I will do next is to design/implement a local implementation of this with the small data set that we have. I will likely omit a lot of tables that are not relevant but try to stick to being HSDS compliant. The only thing I think we might need to "extend" is the concept of "recently available items".

If there is ever a centrally hosted [HSDA](https://openreferral.readthedocs.io/en/latest/hsda/), we could proxy most of our requests to that while maintaining a local database for "recently arrived items". In the shorter term, it may make sense for us to start with our own local database modeled in an HSDS compliant way, then evolve later to perhaps synchronizing with a centrally hosted HSDA via background or scheduled jobs, and then eventually maybe we could migrate to straight up proxying all requests straight to the HSDA. Those are just some initial thoughts.

**Comment by iritush** [comment]
Thanks for the great summary @thomascchen. This all makes sense. Let us know how it goes and if you need any feedback

**Comment by thomascchen** [comment]
@iritush Took me a long time, but I did give the HSDS data model a good try in this PR: https://github.com/codeforUV/food_resources/pull/78

Ultimately, I found it a bit too cumbersome to work with for our current needs, so ended up reverting it, but happy to provide more feedback if interested.

**Comment by iritush** [comment]
Thank you, @thomascchen. Very much appreciated! We are not actively working on this project at the moment but will reach out to you when we work on it again
