### ISSUE TITLE
Set up rspec

### ISSUE THREAD

**Issue by siobhanjacobson** [codeforUV/food_resources#68]
I'll probably start with model tests.

**Comment by siobhanjacobson** [comment]
@thomascchen I think [factory_bot](https://github.com/thoughtbot/factory_bot) and [shoulda-matchers](https://github.com/thoughtbot/shoulda-matchers) would also be very useful.  Is it okay if I add those gems as well?

**Comment by siobhanjacobson** [comment]
I'm running into issues with Ruby and Rails being too new for rspec. I think we can make it work if we use the development branch. https://stackoverflow.com/a/65895657

**Comment by thomascchen** [comment]
Hmm I'm using RSpec with Rails 6.1 on another app with Ruby 2.7.2. I wonder if it's Ruby 3 that's the problem, although that would surprise me...

**Comment by thomascchen** [comment]
Oh I read the issue now... we could try that branch. I'd also be okay with trying out minitest. I've always used RSpec but maybe minitest is fine too?

**Comment by siobhanjacobson** [comment]
I'm running into issues with other dependencies when trying to use the branch in the following PR.  Hopefully it'll be merged in soon (the latest discussion was only 4 days ago). https://github.com/rspec/rspec-rails/pull/2398

**Comment by siobhanjacobson** [comment]
If not, I'll switch gears and try minitest out.

**Comment by siobhanjacobson** [comment]
Edit -- I misread the latest comment in the rspec PR.  It hasn't been released yet.
