### ISSUE TITLE
Bump various vulnerable gems

### ISSUE THREAD

**Issue by siobhanjacobson** [codeforUV/food_resources#74]
![Screenshot from 2021-03-31 19-44-17](https://user-images.githubusercontent.com/28983835/113224465-840b2680-9259-11eb-9a62-20aff25a33e2.png)

**Comment by thomascchen** [comment]
I upgraded the app to Rails 7, ripped out webpacker in favor of import-maps. No more Node, no more javascript vulnerabilities :)
